#!/bin/bash

if [ -z "$3" ]
  then echo "Usage: [task] [network_file] [gpu]"; exit 0
fi
env=$1
network=$2
gpu=$3

args="-env ${env} -network ${network} -gpu ${gpu}"
echo $args
PYTHONPATH=$PWD/util qlua test.lua $args ${4} ${5} ${6} ${7} ${8} ${9} ${10} 
