#!/bin/bash

if [ -z "$5" ]
  then echo "Usage: [train_task] [test_task] [model_name] [lr] [gpu]"; exit 0
fi
env=$1
test_env=$2
name=$3
lr=$4
gpu=$5
hist_len=10
test_hist_len=10
network="$name"
seed=1
replay_memory=1000000
eps_end=0.1
eps_endt=$replay_memory
state_dim=3072
batch_size=32
save_name=$env_$name
agent_params="lr=$lr,ep=1,ep_end=$eps_end,ep_endt=$eps_endt,hist_len=$hist_len,replay_memory=$replay_memory,network="\"$network\"",state_dim=$state_dim,minibatch_size=$batch_size"
steps=25000000

args="-save_name $save_name -env $env -agent_params $agent_params -steps $steps -gpu $gpu -seed $seed -test_env $test_env -test_hist_len $test_hist_len"
echo $args

th train.lua $args
