#!/bin/bash

if [ -z "$2" ]
  then echo "Usage: [model_name] [gpu]"; exit 0
fi
env="IMaze"
test_env="IMazeTest"
name=$1
gpu=$2
hist_len=12

if [ $name = "dqn" ]
then
  lr=0.00025
  test_hist_len=12
else
  lr=0.0005
  test_hist_len=50
fi

network="$name"
seed=1
steps=15000000
replay_memory=50000
state_dim=3072
batch_size=32
save_name=${env}_${name}
agent_params="lr=$lr,hist_len=$hist_len,replay_memory=$replay_memory,network="\"$network\"",state_dim=$state_dim,minibatch_size=$batch_size"
args="-save_name $save_name -env $env -agent_params $agent_params -steps $steps -gpu $gpu -seed $seed -test_env $test_env -test_hist_len $test_hist_len"
echo $args

th train.lua $args
