#!/bin/bash

if [ -z "$4" ]
  then echo "Usage: [train_task] [test_task] [lr] [gpu]"; exit 0
fi
ENV=$1
TEST_ENV=$2
lr=$3
gpu=$4
hist_len=10
test_hist_len=10
network="dqn"
seed=1
replay_memory=1000000
eps_end=0.1
eps_endt=$replay_memory
state_dim=3072
batch_size=32
save_name=${network}_$1
agent_params="lr=$lr,ep=1,ep_end=$eps_end,ep_endt=$eps_endt,hist_len=$hist_len,replay_memory=$replay_memory,network="\"$network\"",state_dim=$state_dim,minibatch_size=$batch_size"
steps=25000000

args="-save_name $save_name -env $ENV -agent_params $agent_params -steps $steps -gpu $gpu -seed $seed -test_env $TEST_ENV -test_hist_len $test_hist_len"
echo $args

th train.lua $args
